name: Update Samsung Kernel

on: 
   workflow_dispatch:

jobs:
   build-kernel:
      runs-on: ubuntu-latest
      steps:
         - name: Install The Dependencies
           run: |
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential flex git curl libssl-dev libelf-dev python3 linux-headers-$(uname -r)
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            echo "$HOME/bin" >> $GITHUB_PATH

         - name: Download GKI From AOSP
           run: |
            mkdir android-kernel
            repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6-2026-04 --depth=1
            repo sync -c -j$(nproc) --no-tags --no-clone-bundle

         - name: Clone Drivers From Samsung Repo
           run: |
             cd android-kernel
             git clone https://github.com/awtismn/gta9pwifi_kernel.git samsung-source
             echo "Repo Cloned, Now Cloning Modules..."
             mkdir -p modules/samsung-d
             cp -r samsung-source/techpack modules/samsung-d
             cp -r samsung-source/include modules/samsung-d
             mkdir -p modules/samsung-d/drivers/soc
             cp -r samsung-source/drivers/soc/qcom modules/samsung-d/drivers/soc
             mkdir -p modules/samsung-d/drivers
             cp -r samsung-source/drivers/media/ modules/samsung-d/drivers
             echo "Cloned Drivers, Removing Cloned Repo (To Save Space)"
             rm -rf samsung-source/
             echo "Done. Next Step"
         - name: Creating Neccessary KLeaf Files
           run: |
             cd android-kernel/modules/samsung-d
             echo "Creating BUILD files"
             cat <<EOF > BUILD.bazel
             load("//build/kernel/kleaf:kernel.bzl","ddk_headers", "ddk_module", "kernel_module", "kernel_images", "kernel_modules_install")

             package(default_visibility = ["//visibility:public"])

             ddk_headers(
             name = "gki_headers",
             hdrs = ["//common:all_headers"],
             )
             
             ddk_module(
              name = "qcom_audio_module",
              srcs = glob(["techpack/audio/**/*.c", "techpack/audio/**/*.h"]),
              out = "qcom_audio.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack/",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/include",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/include/aosc",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/include/dsp",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/include/ipc",
              "-Iandroid-kernel/modules/samsung-d/techpsck/audio/include/soc",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/aosc",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/dsp",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/ipc",
              "-Iandroid-kernel/modules/samsung-d/techpack/audio/soc",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             ddk_module(
              name = "qcom_camera_module",
              srcs = glob(["techpack/camera/drivers/**/*.c", "techpack/camera/drivers/**/*.h"]),
              out = "qcom_camera.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers/cam_cdm",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers/cam_core",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers/cam_cpas",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers/cam_cust",
              "-Iandroid-kernel/modules/samsung-d/techpack/camera/drivers/cam_fd",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             ddk_module(
              name = "qcom_dataipa_module",
              srcs = glob(["techpack/dataipa/**/*.c", "techpack/dataipa/**/*.h"]),
              out = "qcom_dataipa.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack",
              "-Iandroid-kernel/modules/samsung-d/techpack/dataipa",
              "-Iandroid-kernel/modules/samsung-d/techpack/dataipa/drivers",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             ddk_module(
              name = "qcom_display_module",
              srcs = glob(["techpack/display/**/*.c", "techpack/display/**/*.h"]),
              out = "qcom_display.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack",
              "-Iandroid-kernel/modules/samsung-d/techpack/display",
              "-Iandroid-kernel/modules/samsung-d/techpack/display/hdcp",
              "-Iandroid-kernel/modules/samsung-d/techpack/display/msm",
              "-Iandroid-kernel/modules/samsung-d/techpack/display/include",
              "-Iandroid-kernel/modules/samsung-d/techpack/display/rotator",
              "-Iandroid-kernel/modules/samsung-d/techpack/display/tinydrm",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             ddk_module(
              name = "qcom_video_module",
              srcs = glob(["techpack/video/**/*.c", "techpack/video/**/*.h"]),
              out = "qcom_video.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack",
              "-Iandroid-kernel/modules/samsung-d/techpack/video/include",
              "-Iandroid-kernel/modules/samsung-d/techpack/video/msm",
              "-Iandroid-kernel/modules/samsung-d/techpack/video/msm/vidc",
              "-Iandroid-kernel/modules/samsung-d/drivers/soc/qcom",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             ddk_module(
              name = "qcom_stub_module",
              srcs = glob(["techpack/stub/**/*.c", "techpack/stub/**/*.h"]),
              out = "qcom_stub.ko",
              deps = [":gki_headers"],
              kernel_build = "//common:kernel_aarch64",
              copts = [
              "-Iandroid-kernel/modules/samsung-d/include/linux",
              "-Iandroid-kernel/modules/samsung-d/linux",
              "-Iandroid-kernel/modules/samsung-d/techpack",
              "-Iandroid-kernel/modules/samsung-d/techpack/stub",
              "-Iandroid-kernel/modules/samsung-d/techpack/stub/include",
              "-Wno-error",
              "-Wno-unused-function",
              "-Wno-unused-variable",
              "-Wno-declaration-after-statement",
              ],
             )
             
             kernel_modules_install(
             name = "samsung_modules_install",
             kernel_modules = [
             ":qcom_audio_module",
             ":qcom_camera_module",
             ":qcom_dataipa_module",
             ":qcom_display_module",
             ":qcom_video_module",
             ":qcom_stub_module",
             ],
             kernel_build = "//common:kernel_aarch64",
             )
             kernel_images(
             name = "samsung_boot_images",
             build_vendor_boot = True,
             build_initramfs = True,
             kernel_modules_install = ":samsung_modules_install",
             kernel_build = "//common:kernel_aarch64",
             )
             EOF
             if [ -f "BUILD.bazel" ]; then echo "Created BUILD.bazel"; fi
             cat <<EOF > vendor_boot.modules.load
             qcom_stub.ko
             qcom_audio.ko
             qcom_display.ko
             qcom_video.ko
             qcom_camera.ko
             qcom_dataipa.ko
             EOF
             if [ -f "vendor_boot.modules.load" ]; then echo "Created vendor_boot.modules.load"; fi
         - name: Setup Bazel
           uses: bazel-contrib/setup-bazel@main
           with:
             repository-cache: false
             
         - name: Compile Images With Bazel
           run: |
              rm -rf /home/runner/work/Samsung-Kernel-Updater/Samsung-Kernel-Updater/out/cache
              rm -rf /home/runner/work/Samsung-Kernel-Updater/Samsung-Kernel-Updater/out/bazel
              bazel clean --expunge
              
              bazel build //android-kernel/modules/samsung-d:samsung_boot_images --config=fast --sandbox_debug --define=KLEAF_WARN_UNDECLARED_OUTPUTS=true
              image_file=$(find android-kernel -type f -name "Image")
              vendor_file=$find android-kernel -type f -name "vendor_boot.img")
         - name: Uploading Images
           uses: actions/upload-artifact@v4
           with:
             name: Samsung-Images
             path: |
               $image_file
               $vendor_file
               
