name: Update Samsung Kernel

on: 
   workflow_dispatch:

jobs:
   build-kernel:
      runs-on: ubuntu-latest
      steps:
         - name: Free Space
           uses: endersonmenezes/free-disk-space@v3
           with:
             remove_android: true
             remove_dotnet: true
             remove_haskell: true
             remove_tool_cache: true
             remove_swap: true
             remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
             remove_packages_one_command: true
             rm_cmd: "rmz"
             rmz_version: "3.1.1"
             
         - name: Install The Dependencies
           run: |
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential flex git curl libssl-dev libelf-dev python3 linux-headers-$(uname -r)
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            echo "$HOME/bin" >> $GITHUB_PATH

         - name: Download GKI From AOSP
           run: |
            git clone https://github.com/awtismn/gta9pwifi_platform.git android-kernel
            cd android-kernel
            rm -rf .repo
            repo init -u https://android.googlesource.com/kernel/manifest -b common-android15-6.6-2026-04 --depth=1
            repo sync -c -j$(nproc) --no-tags --no-clone-bundle --verbose --fetch-submodules
         - name: Clone Drivers From Samsung Repo
           run: |
             cd android-kernel
             git clone https://github.com/awtismn/gta9pwifi_kernel.git samsung-source
             
             echo "Repo Cloned, Now Cloning Modules..."
             mkdir -p modules/samsung-d
             cp -r samsung-source/techpack modules/samsung-d
             echo "Cloned Modules, Removing Cloned Repo (To Save Space)"
             rm -rf samsung-source/
             find modules/samsung-d -name "Makefile" -delete
             find modules/samsung-d -name "Kbuild" -type f -delete
             echo "Done. Next Step"
         - name: Creating Neccessary KLeaf Files
           run: |
             cd android-kernel
             touch BUILD.bazel
             cat <<'EOF' > BUILD.bazel
             load("//build/kernel/kleaf:kernel.bzl", "ddk_module", "kernel_images", "kernel_modules_install")
             package(default_visibility = ["//visibility:public"])
             filegroup(
             name = "platform_headers",
             srcs = glob([
             "vendor/**/*.h",
             "frameworks/**/*.h",
             "system/**/*.h",
             ]),
             visibility = ["//visibility:public"],
             )
             kernel_module(
             name = "qcom_audio_module",
             srcs = glob(["**/*.c", "**/*.h"]), 
             kernel_build = "//common:kernel_aarch64",
             includes = ["//:platform_headers"],
             out = "qcom_audio.ko",
             )
             kernel_module(
             name = "qcom_camera_module",
             srcs = glob(["**/*.c", "**/*.h"]), 
             kernel_build = "//common:kernel_aarch64",
             includes = ["//:platform_headers"],
             out = "qcom_camera.ko",
             )
             kernel_module(
             name = "qcom_dataipa_module",
             srcs = glob(["**/*.c", "**/*.h"]),
             kernel_build = "//common:kernel_aarch64",
             includes = ["//:platform_headers"],
             out = "qcom_dataipa.ko",
             )
             kernel_module(
             name = "qcom_display_module",
             srcs = glob(["**/*.c", "**/*.h"]),
             kernel_build = "//common:kernel_aarch64",
             includes = ["//:platform_headers"],
             out = "qcom_display.ko",
             )
             kernel_modules_install(
             name = "samsung_modules_install",
             kernel_modules = [
              ":qcom_audio_module",
              ":qcom_camera_module",
              ":qcom_dataipa_module",
              ":qcom_display_module",
             ],
             kernel_build = "//common:kernel_aarch64",
             )
             kernel_images(
             name = "samsung_boot_images",
             build_vendor_boot = True,
             build_initramfs = True,
             kernel_modules_install = ":samsung_modules_install",
             kernel_build = "//common:kernel_aarch64",
             )
             EOF
             if [ -f "BUILD.bazel" ]; then echo "Created BUILD.bazel"; fi
             cat <<'EOF' > vendor_boot.modules.load
             qcom_audio.ko
             qcom_display.ko
             qcom_camera.ko
             qcom_dataipa.ko
             EOF
             if [ -f "vendor_boot.modules.load" ]; then echo "Created vendor_boot.modules.load"; fi
         - name: Setup Bazel
           uses: bazel-contrib/setup-bazel@main
           with:
             repository-cache: false
             
         - name: Compile Images With Bazel
           run: |
              cd android-kernel
              bazel clean --expunge
              bazel build //:samsung_boot_images
              find . -name "Image" > image_path.txt
              find . -name "vendor_boot.img" > vendor_path.txt
         - name: Uploading Images
           uses: actions/upload-artifact@v4
           with:
             name: Samsung-Images
             path: |
               **/Image
               **/vendor_boot.img
