name: Update Samsung Kernel

on: 
   workflow_dispatch:

jobs:
   build-kernel:
      runs-on: ubuntu-latest
      steps:
         - name: Install The Dependencies
           run: |
            sudo apt-get update
            sudo apt-get install -y bc bison build-essential flex git curl libssl-dev libelf-dev python3 linux-headers-$(uname -r)
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            echo "$HOME/bin" >> $GITHUB_PATH

         - name: Download GKI From AOSP
           run: |
            mkdir android-kernel
            repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-2026-04 --depth=1
            repo sync -c -j$(nproc) --no-tags --no-clone-bundle

         - name: Clone Drivers From Samsung Repo
           run: |
             cd android-kernel
             git clone https://github.com/awtismn/gta9pwifi_kernel.git samsung-source
             echo "Repo Cloned, Now Cloning Modules..."
             mkdir -p modules/samsung-d
             cp -r samsung-source/techpack modules/samsung-d
             echo "Cloned Modules, Removing Cloned Repo (To Save Space)"
             rm -rf samsung-source/
             find modules/samsung-d -name "Makefile" -delete
             find modules/samsung-d -name "Kbuild" -type f -delete
             echo "Done. Next Step"
         - name: Creating Neccessary KLeaf Files
           run: |
             cd android-kernel
             echo "Creating BUILD files"
             cat <<'EOF' > WORKSPACE
             load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
             workspace(name = "android_kernel")
             
             EOF
             cd android-kernel/modules/samsung-d
             cat <<'EOF' > BUILD.bazel
             load("//build/kernel/kleaf:kernel.bzl", "ddk_module", "kernel_images", "kernel_modules_install")
             package(default_visibility = ["//visibility:public"])
             ddk_module(
             name = "qcom_audio_module",
             srcs = glob(["techpack/audio/**/*.c", "techpack/audio/**/*.h"]), 
             kernel_build = "//:kernel_aarch64",
             includes = ["techpack/audio/include"],
             out = "qcom_audio.ko",
             )
             ddk_module(
             name = "qcom_camera_module",
             srcs = glob(["techpack/camera/drivers/**/*.c", "techpack/camera/drivers/**/*.h"]), 
             kernel_build = "//:kernel_aarch64",
             includes = ["techpack/camera/drivers"],
             out = "qcom_camera.ko",
             )
             ddk_module(
             name = "qcom_dataipa_module",
             srcs = glob(["techpack/dataipa/**/*.c", "techpack/dataipa/**/*.h"]),
             kernel_build = "//:kernel_aarch64",
             includes = ["techpack/dataipa"],
             out = "qcom_dataipa.ko",
             )
             ddk_module(
             name = "qcom_display_module",
             srcs = glob(["techpack/display/**/*.c", "techpack/display/**/*.h"]),
             kernel_build = "//:kernel_aarch64",
             includes = ["techpack/display"],
             out = "qcom_display.ko",
             )
             kernel_modules_install(
             name = "samsung_modules_install",
             kernel_modules = [
              ":qcom_audio_module",
              ":qcom_camera_module",
              ":qcom_dataipa_module",
              ":qcom_display_module",
             ],
             kernel_build = "//common:kernel_aarch64",
             )
             kernel_images(
             name = "samsung_boot_images",
             build_vendor_boot = True,
             build_initramfs = True,
             kernel_modules_install = ":samsung_modules_install",
             kernel_build = "//common:kernel_aarch64",
             )
             EOF
             if [ -f "BUILD.bazel" ]; then echo "Created BUILD.bazel"; fi
             cat <<'EOF' > vendor_boot.modules.load
             qcom_audio.ko
             qcom_display.ko
             qcom_camera.ko
             qcom_dataipa.ko
             EOF
             if [ -f "vendor_boot.modules.load" ]; then echo "Created vendor_boot.modules.load"; fi
         - name: Setup Bazel
           uses: bazel-contrib/setup-bazel@main
           with:
             repository-cache: false
             
         - name: Compile Images With Bazel
           run: |
              bazel clean --expunge
              bazel build //modules/samsung-d:samsung_boot_images
              find . -name "Image" > image_path.txt
              find . -name "vendor_boot.img" > vendor_path.txt
         - name: Uploading Images
           uses: actions/upload-artifact@v4
           with:
             name: Samsung-Images
             path: |
               **/Image
               **/vendor_boot.img
